#!/usr/bin/env python3
"""Validate M3.3 science mission runtime and rainforest ecosystem mission contracts."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SCIENCE_CANONICAL = ROOT / "content/missions/science/rainforest-ecosystem-01.json"
SCIENCE_PACKAGED = ROOT / "game/Content/WorldMakers/Missions/mission.science.rainforest-ecosystem-01.json"
BIOME_CANONICAL = ROOT / "content/biomes/caribbean-rainforest/runtime.json"
BIOME_PACKAGED = ROOT / "game/Content/WorldMakers/Biomes/biome.caribbean-rainforest.json"
MISSION_SCHEMA = ROOT / "content/missions/schema/mission.schema.json"

REQUIRED_FILES = [
    "game/Source/WorldMakers/Mission/WMMissionTypes.h",
    "game/Source/WorldMakers/Mission/WMMissionTypes.cpp",
    "game/Source/WorldMakers/Mission/WMMissionRuntimeSubsystem.h",
    "game/Source/WorldMakers/Mission/WMMissionRuntimeSubsystem.cpp",
    "game/Source/WorldMakers/Mission/WMMissionObservationAdapterSubsystem.h",
    "game/Source/WorldMakers/Mission/WMMissionObservationAdapterSubsystem.cpp",
    "game/Source/WorldMakers/Private/Tests/WMScienceMissionTests.cpp",
    "docs/m3-3-science-mission-runtime.md",
]


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def main() -> None:
    for relative in REQUIRED_FILES:
        require((ROOT / relative).is_file(), f"Missing M3.3 file: {relative}")

    for path in (SCIENCE_CANONICAL, SCIENCE_PACKAGED, BIOME_CANONICAL, BIOME_PACKAGED, MISSION_SCHEMA):
        require(path.is_file(), f"Missing M3.3 contract file: {path.relative_to(ROOT)}")

    require(SCIENCE_CANONICAL.read_bytes() == SCIENCE_PACKAGED.read_bytes(), "Packaged science mission must be byte-equivalent to canonical source")
    require(BIOME_CANONICAL.read_bytes() == BIOME_PACKAGED.read_bytes(), "Packaged biome must remain byte-equivalent to canonical source")

    schema = json.loads(MISSION_SCHEMA.read_text(encoding="utf-8"))
    runtime_schema = schema["properties"]["runtime"]
    runtime_required = set(runtime_schema["required"])
    evaluator_values = set(runtime_schema["properties"]["evaluator"]["enum"])
    require({"evaluator", "rewardIds", "prototypeOnly"}.issubset(runtime_required), "Mission runtime must retain core required fields")
    require("targetSpanCm" not in runtime_required and "toleranceCm" not in runtime_required, "Math span fields must not be globally required for non-math evaluators")
    require({"measure-and-build", "observe-ecosystem"}.issubset(evaluator_values), "Mission schema must support both mathematics and science evaluators")
    observation_schema = runtime_schema["properties"].get("observationRequirements")
    require(isinstance(observation_schema, dict) and observation_schema.get("minItems", 0) >= 2, "Science evaluator requires an observationRequirements contract")
    observation_item_required = set(observation_schema["items"]["required"])
    require(observation_item_required == {"observationId", "evidenceEventId", "objectiveId"}, "Observation requirement must map observation -> evidence -> objective")

    science = json.loads(SCIENCE_CANONICAL.read_text(encoding="utf-8"))
    require(science["id"] == "mission.science.rainforest-ecosystem-01", "M3.3 science mission ID changed unexpectedly")
    require(science["axis"] == "science", "M3.3 mission must remain on science axis")
    require(science["analyticsClassification"] == "minimized-learning-evidence", "Science mission must use minimized learning evidence")
    runtime = science["runtime"]
    require(runtime["evaluator"] == "observe-ecosystem", "Science mission must use observe-ecosystem evaluator")
    require("targetSpanCm" not in runtime and "toleranceCm" not in runtime, "Science mission must not carry mathematics span fields")
    require(runtime.get("prototypeOnly") is True, "Draft M3.3 science mission must remain prototypeOnly")
    requirements = runtime.get("observationRequirements", [])
    require(len(requirements) == 3, "Rainforest science mission must require exactly three deliberate observations")

    observation_ids = [item["observationId"] for item in requirements]
    evidence_ids = [item["evidenceEventId"] for item in requirements]
    require(len(observation_ids) == len(set(observation_ids)), "Science observation IDs must be unique")
    require(len(evidence_ids) == len(set(evidence_ids)), "Science evidence event IDs must be unique")
    require(set(evidence_ids) == set(science["evidenceEvents"]), "Every science evidence event must be generated by an observation requirement")
    require(all(item["objectiveId"] in science["learningObjectives"] for item in requirements), "Observation requirements must map only to declared learning objectives")

    biome = json.loads(BIOME_CANONICAL.read_text(encoding="utf-8"))
    biome_observations = {point.get("observationId") for point in biome.get("pointsOfInterest", []) if point.get("requiresInteraction") is True}
    require(set(observation_ids).issubset(biome_observations), "Science mission requirements must reference real deliberate biome observations")
    science_zones = [zone for zone in biome.get("zones", []) if science["id"] in zone.get("missionIds", [])]
    require(len(science_zones) >= 3, "Science mission must be discoverable across the three relevant rainforest semantic zones")

    rewards = json.loads(read("content/economy/rewards/default-rewards.json"))
    reward_by_id = {item["rewardId"]: item for item in rewards}
    for reward_id in runtime["rewardIds"]:
        require(reward_id in reward_by_id, f"Science mission references unknown reward: {reward_id}")
        reward = reward_by_id[reward_id]
        require(reward.get("deterministic") is True, "Science reward must be deterministic")
        require(reward.get("purchasable") is False, "Science reward must not be purchasable")
        require(reward.get("transferable") is False, "Science reward must not be transferable")
        require(reward.get("convertibleToMoney") is False, "Science reward must not convert to money")
        require(reward.get("streakRequired") is False, "Science reward must not use streak pressure")
        require(reward.get("expiresAt") is None, "Science reward must not expire")
        require(reward.get("trigger", {}).get("missionId") == science["id"], "Science reward must be bound to the science mission")

    types_h = read("game/Source/WorldMakers/Mission/WMMissionTypes.h")
    types_cpp = read("game/Source/WorldMakers/Mission/WMMissionTypes.cpp")
    for token in (
        "FWMObservationEvidenceRequirement",
        "FName Evaluator",
        "ObservationRequirements",
        "RecordedObservationIds",
        "RecordObservation",
        "IsMeasureAndBuild",
        "IsObserveEcosystem",
        "FindObservationRequirement",
    ):
        require(token in types_h or token in types_cpp, f"Mission multi-evaluator model missing: {token}")
    require("RecordedObservationIds.Contains" in types_cpp, "Science observations must be idempotent")
    require("RecordedObservationIds.Num() == Definition.ObservationRequirements.Num()" in types_cpp, "Science mission must complete only after all required observations")
    require("Definition.IsMeasureAndBuild()" in types_cpp, "Legacy mathematics evaluator must remain explicitly guarded")

    runtime_h = read("game/Source/WorldMakers/Mission/WMMissionRuntimeSubsystem.h")
    runtime_cpp = read("game/Source/WorldMakers/Mission/WMMissionRuntimeSubsystem.cpp")
    for token in ("RecordObservationEvidence", "IsObservationRequired", "GetRequiredObservationIds", "GetRecordedObservationCount", "GetActiveEvaluator"):
        require(token in runtime_h or token in runtime_cpp, f"Mission runtime science API missing: {token}")
    require("FinalizeMissionCompletion" in runtime_cpp and "Progress.RecordObservation" in runtime_cpp, "Science completion must flow through the existing journey completion path")

    adapter_h = read("game/Source/WorldMakers/Mission/WMMissionObservationAdapterSubsystem.h")
    adapter_cpp = read("game/Source/WorldMakers/Mission/WMMissionObservationAdapterSubsystem.cpp")
    require("UWMMissionObservationAdapterSubsystem" in adapter_h, "M3.3 mission-side adapter missing")
    require("OnObservationRegistered.AddDynamic" in adapter_cpp, "Mission adapter must subscribe to biome observation events")
    require("RecordObservationEvidence" in adapter_cpp and "IsObservationRequired" in adapter_cpp, "Mission adapter must forward only relevant stable observations")
    require("Environment/WMBiomeRuntimeSubsystem.h" in adapter_cpp and "Mission/WMMissionRuntimeSubsystem.h" in adapter_cpp, "Adapter must own the Environment -> Mission dependency edge")

    environment_source = "\n".join(
        path.read_text(encoding="utf-8")
        for path in (ROOT / "game/Source/WorldMakers/Environment").glob("WM*.cpp")
    ) + "\n" + "\n".join(
        path.read_text(encoding="utf-8")
        for path in (ROOT / "game/Source/WorldMakers/Environment").glob("WM*.h")
    )
    require("Mission/WMMissionRuntimeSubsystem" not in environment_source, "Environment must remain mission-agnostic; dependency belongs in mission adapter")

    hud = read("game/Source/WorldMakers/UI/WMBuildHUDWidget.cpp")
    require("observe-ecosystem" in hud and "GetRecordedObservationCount" in hud and "GetRequiredObservationIds" in hud, "Child HUD must show evaluator-aware science progress")

    tests = read("game/Source/WorldMakers/Private/Tests/WMScienceMissionTests.cpp")
    for test_name in (
        "WorldMakers.Missions.Science.Definition.ParsesObservationEvaluator",
        "WorldMakers.Missions.Science.Progress.OrderIndependentIdempotentObservations",
        "WorldMakers.Missions.Science.Regression.MeasureAndBuildStillWorks",
    ):
        require(test_name in tests, f"Missing M3.3 automation test: {test_name}")

    repo_ci = read(".github/workflows/repo-quality.yml")
    unreal_ci = read(".github/workflows/unreal-ci.yml")
    require("validate-m3-3-science-mission-runtime.py" in repo_ci and "validate-m3-3-science-mission-runtime.py" in unreal_ci, "M3.3 validator must run in Repository Quality and Unreal CI")

    docs = read("docs/m3-3-science-mission-runtime.md").lower()
    for boundary in ("issue #9", "observe-ecosystem", "stable ids", "no xp", "environment", "mission"):
        require(boundary in docs, f"M3.3 documentation boundary missing: {boundary}")

    print("M3.3 science mission runtime validated: multi-evaluator schema, three deliberate rainforest observations, idempotent evidence, mission-side adapter, Trust Economy reward and CI gates are wired.")


if __name__ == "__main__":
    main()
